### ISSUE TITLE
DB configuration for liferay container

### ISSUE THREAD

**Issue by mdelapenya** [sammonsjl/demo-liferay#1]
Hey @sammonsjl, I'd like to let you know that if you are going to add your own database (in this case MariaDB), then you should extend the HSQL image instead.

Take a look at the source code of the MySQL branch: https://github.com/mdelapenya/docker-liferay-portal/tree/7-ce-ga4-tomcat-mysql. I'm already adding the portal-ext with db configuration.

Please tell me if you have any question or suggestion

Thanks!

**Comment by sammonsjl** [comment]
Hey @mdelapenya, good point!  I never thought to base it on the HSQL image.  I have made the change.  Thanks for the suggestion.
